import type { Metadata } from "next";
import { Open_Sans, Bitter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const openSans = Open_Sans({ subsets: ["latin"] });

export const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pub Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        <div className="container mx-auto py-10">{children}</div>
      </body>
    </html>
  );
}
